# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [12]:
#code here
import numpy as np
ran=np.random.randint(99,size=12)
print("1d array\n\n",ran)
print("\n\nRESIZED 3x4 array\n\n",ran.reshape(3,4))

1d array

 [55 49 84 82 40 10 80 11 13 14 33  9]


RESIZED 3x4 array

 [[55 49 84 82]
 [40 10 80 11]
 [13 14 33  9]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [18]:
def classify_emails(emails):
    # Spam Keywords
    spam=[]
    imp=[]
    promo=[]
    # Spam Keywords
    spam_keywords = [
        "nigerian prince",
        "free money",
        "enlarge",
        "make money fast",
        "guaranteed",
        "click here",
        "limited time offer",
        "congratulations, you've won",
        "unsubscribe"
    ]

    # Promotions Keywords
    promotions_keywords = [
        "sale",
        "discount",
        "deal",
        "offer",
        "promo",
        "clearance",
        "coupon",
        "limited time",
        "special",
        "exclusive"
    ]

    # Important Keywords
    important_keywords = [
        "urgent",
        "action required",
        "deadline",
        "confirmation",
        "invoice",
        "payment",
        "meeting",
        "appointment",
        "contract",
        "emergency"
    ]

    for i in emails:
        for f in spam_keywords:
            if i.lower().__contains__(f):
                spam.append(i)
        for f in important_keywords:
            if i.lower().__contains__(f):
                imp.append(i)
        for f in promotions_keywords:
            if i.lower().__contains__(f):
                promo.append(i)

    return spam, imp, promo

test_emails = [
    "Hello, urgent meeting tomorrow.",
    "Get a special discount on our products!",
    "Congratulations! You've won $1000!",
    "Enlarge your savings with our limited time offer.",
    "Invoice for your recent purchase.",
    "Nigerian prince needs your help.",
    "Reminder: Action required for your contract.",
    "Exclusive deals just for you.",
    "Free money offer inside.",
    "Important deadline approaching."
]

spam, important, promotions = classify_emails(test_emails)

print("Important Emails:")
print(important)
print("\nPromotions Emails:")
print(promotions)
print("\nSpam Emails:")
print(spam)


Important Emails:
['Hello, urgent meeting tomorrow.', 'Hello, urgent meeting tomorrow.', 'Invoice for your recent purchase.', 'Reminder: Action required for your contract.', 'Reminder: Action required for your contract.', 'Important deadline approaching.']

Promotions Emails:
['Get a special discount on our products!', 'Get a special discount on our products!', 'Enlarge your savings with our limited time offer.', 'Enlarge your savings with our limited time offer.', 'Exclusive deals just for you.', 'Exclusive deals just for you.', 'Free money offer inside.']

Spam Emails:
['Enlarge your savings with our limited time offer.', 'Enlarge your savings with our limited time offer.', 'Nigerian prince needs your help.', 'Free money offer inside.']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [38]:
#code here

english_spanish_dict = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "please": "por favor",
    "yes": "sí",
    "no": "no",
    "house": "casa",
    "cat": "gato",
    "dog": "perro",
    "book": "libro",
    "computer": "computadora",
    "table": "mesa",
    "car": "coche",
    "school": "escuela",
    "teacher": "profesor(a)",
    "student": "estudiante",
    "pencil": "lápiz",
    "phone": "teléfono",
    "work": "trabajar",
    "play": "jugar",
    "music": "música",
    "movie": "película",
    "read": "leer",
    "write": "escribir",
    "learn": "aprender",
    "eat": "comer",
    "drink": "beber",
    "sleep": "dormir",
    "run": "correr",
    "swim": "nadar",
    "jump": "saltar",
    "drive": "conducir",
    "happy": "feliz",
    "sad": "triste",
    "hot": "caliente",
    "cold": "frío",
    "big": "grande",
    "small": "pequeño(a)",
    "good": "bueno(a)",
    "bad": "malo(a)",
    "clean": "limpio(a)",
    "dirty": "sucio(a)",
    "fast": "rápido(a)",
    "slow": "lento(a)",
}
alpha=True;
while alpha:
    word=input("Please enter the word you are looking for:")
    word=word.lower()


    if word in english_spanish_dict:
        print("Translation in Spanish:",english_spanish_dict[word])
    else:
        print("Not found")

    alpha=input("Want to search for more (Enter 0 to quit,or anyother word to continue)")
    if alpha =="0":
          break



Please enter the word you are looking for:hello
Translation in Spanish: hola
Want to search for more (Enter 0 to quit,or anyother word to continue)0


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [42]:
import pandas as pd

# Load the dataset
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)

# Display the DataFrame
df


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

**TOTAL GLOBAL SALES**

In [44]:
df["Global_Sales"].sum()

8920.44

In [48]:
ds=df[df["Global_Sales"]==df["Global_Sales"].max()]
ds

Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).

In [50]:
print("\nNA SALES\n",df["NA_Sales"].mean(),"\nEU SALES\n",df["EU_Sales"].mean(),"\nJP SALES\n",df["JP_Sales"].mean(),"\nOther SALES\n",df["Other_Sales"].mean())


NA SALES
 0.26466742981082064 
EU SALES
 0.14665200626581515 
JP SALES
 0.077781660441017 
Other SALES
 0.0480630196409206


Find the top 5 most popular game genres based on global sales.

In [59]:
a=df.sort_values(by="Global_Sales",ascending=False)
print(a["Genre"].head())

0          Sports
1        Platform
2          Racing
3          Sports
4    Role-Playing
Name: Genre, dtype: object


Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).





In [65]:
genre_sales = df.groupby('Genre').agg({
    'NA_Sales': 'sum','EU_Sales': 'sum','JP_Sales': 'sum','Other_Sales': 'sum','Global_Sales': 'sum'
})
print(genre_sales)

print("\n\n\n\nMost popular genre",genre_sales['NA_Sales'].idxmax())

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre                                                                
Action          877.83    525.00    159.95       187.38       1751.18
Adventure       105.80     64.13     52.07        16.81        239.04
Fighting        223.59    101.32     87.35        36.68        448.91
Misc            410.24    215.98    107.76        75.32        809.96
Platform        447.05    201.63    130.77        51.59        831.37
Puzzle          123.78     50.78     57.31        12.55        244.95
Racing          359.42    238.39     56.69        77.27        732.04
Role-Playing    327.28    188.06    352.31        59.61        927.37
Shooter         582.60    313.27     38.28       102.69       1037.37
Simulation      183.31    113.38     63.70        31.52        392.20
Sports          683.35    376.85    135.37       134.97       1330.93
Strategy         68.70     45.34     49.46        11.36        175.12




Most popular gen

last 10 rows

In [66]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

Determine the top 3 gaming platforms with the highest global sales.

In [69]:
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False)
print("Top 3 platforms ",platform_sales.head(3))


Top 3 platforms  Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


**Calculate the market share (percentage of global sales) for each genre.**

In [71]:
suum=df["Global_Sales"].sum()
share=(df.groupby("Genre")["Global_Sales"].sum()/suum)*100
share

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

***Calculate the correlation coefficient between NA_Sales and EU_Sales.***

In [74]:
print([df["NA_Sales"].corr(df["EU_Sales"])])


[0.7677267483702631]


In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
